# Generated by Django 4.0.3 on 2022-06-04 23:37

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('metkeyword', models.CharField(max_length=200, null=True)),
                ('header_image', models.ImageField(upload_to='headerimage')),
                ('upload_fonts', models.FileField(null=True, upload_to='media')),
                ('short_discription', models.CharField(max_length=255)),
                ('long_discription', froala_editor.fields.FroalaField()),
                ('character_map_img', models.ImageField(upload_to='characterimage')),
                ('publish', models.BooleanField(default=False, null=True)),
                ('Total_downloads', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websitename', models.CharField(max_length=50)),
                ('ouremail', models.EmailField(max_length=254)),
                ('copyright', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='websiteimages')),
                ('websitediscription', froala_editor.fields.FroalaField()),
                ('favicon', models.ImageField(default='AF', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', froala_editor.fields.FroalaField()),
                ('privacypolicy', froala_editor.fields.FroalaField()),
                ('termsandcondition', froala_editor.fields.FroalaField()),
                ('ourpages', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
